; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 4
; RUN: opt < %s -passes=amdgpu-sw-lower-lds -S -mtriple=amdgcn-amd-amdhsa | FileCheck %s

@lds_1 = internal addrspace(3) global [1 x i32] poison, align 4
@lds_2 = internal addrspace(3) global [1 x i32] poison, align 4

; Test to check if static LDS accesses in kernel are lowered correctly.
;.
; CHECK: @llvm.amdgcn.sw.lds.atomicrmw_kernel = internal addrspace(3) global ptr poison, no_sanitize_address, align 4, !absolute_symbol [[META0:![0-9]+]]
; CHECK: @llvm.amdgcn.sw.lds.atomicrmw_kernel.md = internal addrspace(1) global %llvm.amdgcn.sw.lds.atomicrmw_kernel.md.type { %llvm.amdgcn.sw.lds.atomicrmw_kernel.md.item { i32 0, i32 8, i32 32 }, %llvm.amdgcn.sw.lds.atomicrmw_kernel.md.item { i32 32, i32 4, i32 32 }, %llvm.amdgcn.sw.lds.atomicrmw_kernel.md.item { i32 64, i32 4, i32 32 } }, no_sanitize_address
;.
define amdgpu_kernel void @atomicrmw_kernel(ptr addrspace(1) %arg0) sanitize_address {
; CHECK-LABEL: define amdgpu_kernel void @atomicrmw_kernel(
; CHECK-SAME: ptr addrspace(1) [[ARG0:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  WId:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.amdgcn.workitem.id.x()
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.workitem.id.y()
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.amdgcn.workitem.id.z()
; CHECK-NEXT:    [[TMP3:%.*]] = or i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[TMP4:%.*]] = or i32 [[TMP3]], [[TMP2]]
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i32 [[TMP4]], 0
; CHECK-NEXT:    br i1 [[TMP5]], label [[MALLOC:%.*]], label [[TMP20:%.*]]
; CHECK:       Malloc:
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr addrspace(1) getelementptr inbounds ([[LLVM_AMDGCN_SW_LDS_ATOMICRMW_KERNEL_MD_TYPE:%.*]], ptr addrspace(1) @llvm.amdgcn.sw.lds.atomicrmw_kernel.md, i32 0, i32 2, i32 0), align 4
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr addrspace(1) getelementptr inbounds ([[LLVM_AMDGCN_SW_LDS_ATOMICRMW_KERNEL_MD_TYPE]], ptr addrspace(1) @llvm.amdgcn.sw.lds.atomicrmw_kernel.md, i32 0, i32 2, i32 2), align 4
; CHECK-NEXT:    [[TMP8:%.*]] = add i32 [[TMP6]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP8]] to i64
; CHECK-NEXT:    [[TMP10:%.*]] = call ptr @llvm.returnaddress(i32 0)
; CHECK-NEXT:    [[TMP11:%.*]] = ptrtoint ptr [[TMP10]] to i64
; CHECK-NEXT:    [[TMP12:%.*]] = call i64 @__asan_malloc_impl(i64 [[TMP9]], i64 [[TMP11]])
; CHECK-NEXT:    [[TMP13:%.*]] = inttoptr i64 [[TMP12]] to ptr addrspace(1)
; CHECK-NEXT:    store ptr addrspace(1) [[TMP13]], ptr addrspace(3) @llvm.amdgcn.sw.lds.atomicrmw_kernel, align 8
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[TMP13]], i64 8
; CHECK-NEXT:    [[TMP15:%.*]] = ptrtoint ptr addrspace(1) [[TMP14]] to i64
; CHECK-NEXT:    call void @__asan_poison_region(i64 [[TMP15]], i64 24)
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[TMP13]], i64 36
; CHECK-NEXT:    [[TMP17:%.*]] = ptrtoint ptr addrspace(1) [[TMP16]] to i64
; CHECK-NEXT:    call void @__asan_poison_region(i64 [[TMP17]], i64 28)
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[TMP13]], i64 68
; CHECK-NEXT:    [[TMP19:%.*]] = ptrtoint ptr addrspace(1) [[TMP18]] to i64
; CHECK-NEXT:    call void @__asan_poison_region(i64 [[TMP19]], i64 28)
; CHECK-NEXT:    br label [[TMP20]]
; CHECK:       20:
; CHECK-NEXT:    [[XYZCOND:%.*]] = phi i1 [ false, [[WID:%.*]] ], [ true, [[MALLOC]] ]
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier()
; CHECK-NEXT:    [[TMP21:%.*]] = load ptr addrspace(1), ptr addrspace(3) @llvm.amdgcn.sw.lds.atomicrmw_kernel, align 8
; CHECK-NEXT:    [[TMP22:%.*]] = load i32, ptr addrspace(1) getelementptr inbounds ([[LLVM_AMDGCN_SW_LDS_ATOMICRMW_KERNEL_MD_TYPE]], ptr addrspace(1) @llvm.amdgcn.sw.lds.atomicrmw_kernel.md, i32 0, i32 1, i32 0), align 4
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds i8, ptr addrspace(3) @llvm.amdgcn.sw.lds.atomicrmw_kernel, i32 [[TMP22]]
; CHECK-NEXT:    [[TMP24:%.*]] = load i32, ptr addrspace(1) getelementptr inbounds ([[LLVM_AMDGCN_SW_LDS_ATOMICRMW_KERNEL_MD_TYPE]], ptr addrspace(1) @llvm.amdgcn.sw.lds.atomicrmw_kernel.md, i32 0, i32 2, i32 0), align 4
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i8, ptr addrspace(3) @llvm.amdgcn.sw.lds.atomicrmw_kernel, i32 [[TMP24]]
; CHECK-NEXT:    [[TMP26:%.*]] = load volatile i32, ptr addrspace(1) [[ARG0]], align 4
; CHECK-NEXT:    [[TMP27:%.*]] = ptrtoint ptr addrspace(3) [[TMP23]] to i32
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[TMP21]], i32 [[TMP27]]
; CHECK-NEXT:    [[TMP29:%.*]] = ptrtoint ptr addrspace(1) [[TMP28]] to i64
; CHECK-NEXT:    [[TMP30:%.*]] = add i64 [[TMP29]], 3
; CHECK-NEXT:    [[TMP31:%.*]] = inttoptr i64 [[TMP30]] to ptr addrspace(1)
; CHECK-NEXT:    [[TMP32:%.*]] = ptrtoint ptr addrspace(1) [[TMP28]] to i64
; CHECK-NEXT:    [[TMP33:%.*]] = lshr i64 [[TMP32]], 3
; CHECK-NEXT:    [[TMP34:%.*]] = add i64 [[TMP33]], 2147450880
; CHECK-NEXT:    [[TMP35:%.*]] = inttoptr i64 [[TMP34]] to ptr
; CHECK-NEXT:    [[TMP36:%.*]] = load i8, ptr [[TMP35]], align 1
; CHECK-NEXT:    [[TMP37:%.*]] = icmp ne i8 [[TMP36]], 0
; CHECK-NEXT:    [[TMP38:%.*]] = and i64 [[TMP32]], 7
; CHECK-NEXT:    [[TMP39:%.*]] = trunc i64 [[TMP38]] to i8
; CHECK-NEXT:    [[TMP40:%.*]] = icmp sge i8 [[TMP39]], [[TMP36]]
; CHECK-NEXT:    [[TMP41:%.*]] = and i1 [[TMP37]], [[TMP40]]
; CHECK-NEXT:    [[TMP42:%.*]] = call i64 @llvm.amdgcn.ballot.i64(i1 [[TMP41]])
; CHECK-NEXT:    [[TMP43:%.*]] = icmp ne i64 [[TMP42]], 0
; CHECK-NEXT:    br i1 [[TMP43]], label [[ASAN_REPORT:%.*]], label [[TMP46:%.*]], !prof [[PROF2:![0-9]+]]
; CHECK:       asan.report:
; CHECK-NEXT:    br i1 [[TMP41]], label [[TMP44:%.*]], label [[TMP45:%.*]]
; CHECK:       44:
; CHECK-NEXT:    call void @__asan_report_store1(i64 [[TMP32]]) #[[ATTR6:[0-9]+]]
; CHECK-NEXT:    call void @llvm.amdgcn.unreachable()
; CHECK-NEXT:    br label [[TMP45]]
; CHECK:       45:
; CHECK-NEXT:    br label [[TMP46]]
; CHECK:       46:
; CHECK-NEXT:    [[TMP47:%.*]] = ptrtoint ptr addrspace(1) [[TMP31]] to i64
; CHECK-NEXT:    [[TMP48:%.*]] = lshr i64 [[TMP47]], 3
; CHECK-NEXT:    [[TMP49:%.*]] = add i64 [[TMP48]], 2147450880
; CHECK-NEXT:    [[TMP50:%.*]] = inttoptr i64 [[TMP49]] to ptr
; CHECK-NEXT:    [[TMP51:%.*]] = load i8, ptr [[TMP50]], align 1
; CHECK-NEXT:    [[TMP52:%.*]] = icmp ne i8 [[TMP51]], 0
; CHECK-NEXT:    [[TMP53:%.*]] = and i64 [[TMP47]], 7
; CHECK-NEXT:    [[TMP54:%.*]] = trunc i64 [[TMP53]] to i8
; CHECK-NEXT:    [[TMP55:%.*]] = icmp sge i8 [[TMP54]], [[TMP51]]
; CHECK-NEXT:    [[TMP56:%.*]] = and i1 [[TMP52]], [[TMP55]]
; CHECK-NEXT:    [[TMP57:%.*]] = call i64 @llvm.amdgcn.ballot.i64(i1 [[TMP56]])
; CHECK-NEXT:    [[TMP58:%.*]] = icmp ne i64 [[TMP57]], 0
; CHECK-NEXT:    br i1 [[TMP58]], label [[ASAN_REPORT1:%.*]], label [[TMP61:%.*]], !prof [[PROF2]]
; CHECK:       asan.report1:
; CHECK-NEXT:    br i1 [[TMP56]], label [[TMP59:%.*]], label [[TMP60:%.*]]
; CHECK:       59:
; CHECK-NEXT:    call void @__asan_report_store1(i64 [[TMP47]]) #[[ATTR6]]
; CHECK-NEXT:    call void @llvm.amdgcn.unreachable()
; CHECK-NEXT:    br label [[TMP60]]
; CHECK:       60:
; CHECK-NEXT:    br label [[TMP61]]
; CHECK:       61:
; CHECK-NEXT:    [[TMP62:%.*]] = atomicrmw umin ptr addrspace(1) [[TMP28]], i32 [[TMP26]] seq_cst, align 4
; CHECK-NEXT:    [[TMP63:%.*]] = ptrtoint ptr addrspace(3) [[TMP23]] to i32
; CHECK-NEXT:    [[TMP64:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[TMP21]], i32 [[TMP63]]
; CHECK-NEXT:    [[TMP65:%.*]] = ptrtoint ptr addrspace(1) [[TMP64]] to i64
; CHECK-NEXT:    [[TMP66:%.*]] = add i64 [[TMP65]], 3
; CHECK-NEXT:    [[TMP67:%.*]] = inttoptr i64 [[TMP66]] to ptr addrspace(1)
; CHECK-NEXT:    [[TMP68:%.*]] = ptrtoint ptr addrspace(1) [[TMP64]] to i64
; CHECK-NEXT:    [[TMP69:%.*]] = lshr i64 [[TMP68]], 3
; CHECK-NEXT:    [[TMP70:%.*]] = add i64 [[TMP69]], 2147450880
; CHECK-NEXT:    [[TMP71:%.*]] = inttoptr i64 [[TMP70]] to ptr
; CHECK-NEXT:    [[TMP72:%.*]] = load i8, ptr [[TMP71]], align 1
; CHECK-NEXT:    [[TMP73:%.*]] = icmp ne i8 [[TMP72]], 0
; CHECK-NEXT:    [[TMP74:%.*]] = and i64 [[TMP68]], 7
; CHECK-NEXT:    [[TMP75:%.*]] = trunc i64 [[TMP74]] to i8
; CHECK-NEXT:    [[TMP76:%.*]] = icmp sge i8 [[TMP75]], [[TMP72]]
; CHECK-NEXT:    [[TMP77:%.*]] = and i1 [[TMP73]], [[TMP76]]
; CHECK-NEXT:    [[TMP78:%.*]] = call i64 @llvm.amdgcn.ballot.i64(i1 [[TMP77]])
; CHECK-NEXT:    [[TMP79:%.*]] = icmp ne i64 [[TMP78]], 0
; CHECK-NEXT:    br i1 [[TMP79]], label [[ASAN_REPORT2:%.*]], label [[TMP82:%.*]], !prof [[PROF2]]
; CHECK:       asan.report2:
; CHECK-NEXT:    br i1 [[TMP77]], label [[TMP80:%.*]], label [[TMP81:%.*]]
; CHECK:       80:
; CHECK-NEXT:    call void @__asan_report_store1(i64 [[TMP68]]) #[[ATTR6]]
; CHECK-NEXT:    call void @llvm.amdgcn.unreachable()
; CHECK-NEXT:    br label [[TMP81]]
; CHECK:       81:
; CHECK-NEXT:    br label [[TMP82]]
; CHECK:       82:
; CHECK-NEXT:    [[TMP83:%.*]] = ptrtoint ptr addrspace(1) [[TMP67]] to i64
; CHECK-NEXT:    [[TMP84:%.*]] = lshr i64 [[TMP83]], 3
; CHECK-NEXT:    [[TMP85:%.*]] = add i64 [[TMP84]], 2147450880
; CHECK-NEXT:    [[TMP86:%.*]] = inttoptr i64 [[TMP85]] to ptr
; CHECK-NEXT:    [[TMP87:%.*]] = load i8, ptr [[TMP86]], align 1
; CHECK-NEXT:    [[TMP88:%.*]] = icmp ne i8 [[TMP87]], 0
; CHECK-NEXT:    [[TMP89:%.*]] = and i64 [[TMP83]], 7
; CHECK-NEXT:    [[TMP90:%.*]] = trunc i64 [[TMP89]] to i8
; CHECK-NEXT:    [[TMP91:%.*]] = icmp sge i8 [[TMP90]], [[TMP87]]
; CHECK-NEXT:    [[TMP92:%.*]] = and i1 [[TMP88]], [[TMP91]]
; CHECK-NEXT:    [[TMP93:%.*]] = call i64 @llvm.amdgcn.ballot.i64(i1 [[TMP92]])
; CHECK-NEXT:    [[TMP94:%.*]] = icmp ne i64 [[TMP93]], 0
; CHECK-NEXT:    br i1 [[TMP94]], label [[ASAN_REPORT3:%.*]], label [[TMP97:%.*]], !prof [[PROF2]]
; CHECK:       asan.report3:
; CHECK-NEXT:    br i1 [[TMP92]], label [[TMP95:%.*]], label [[TMP96:%.*]]
; CHECK:       95:
; CHECK-NEXT:    call void @__asan_report_store1(i64 [[TMP83]]) #[[ATTR6]]
; CHECK-NEXT:    call void @llvm.amdgcn.unreachable()
; CHECK-NEXT:    br label [[TMP96]]
; CHECK:       96:
; CHECK-NEXT:    br label [[TMP97]]
; CHECK:       97:
; CHECK-NEXT:    [[TMP98:%.*]] = atomicrmw umax ptr addrspace(1) [[TMP64]], i32 [[TMP26]] seq_cst, align 4
; CHECK-NEXT:    [[TMP99:%.*]] = add i32 [[TMP62]], [[TMP98]]
; CHECK-NEXT:    [[TMP100:%.*]] = ptrtoint ptr addrspace(3) [[TMP25]] to i32
; CHECK-NEXT:    [[TMP101:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[TMP21]], i32 [[TMP100]]
; CHECK-NEXT:    [[TMP102:%.*]] = ptrtoint ptr addrspace(1) [[TMP101]] to i64
; CHECK-NEXT:    [[TMP103:%.*]] = lshr i64 [[TMP102]], 3
; CHECK-NEXT:    [[TMP104:%.*]] = add i64 [[TMP103]], 2147450880
; CHECK-NEXT:    [[TMP105:%.*]] = inttoptr i64 [[TMP104]] to ptr
; CHECK-NEXT:    [[TMP106:%.*]] = load i8, ptr [[TMP105]], align 1
; CHECK-NEXT:    [[TMP107:%.*]] = icmp ne i8 [[TMP106]], 0
; CHECK-NEXT:    [[TMP108:%.*]] = and i64 [[TMP102]], 7
; CHECK-NEXT:    [[TMP109:%.*]] = add i64 [[TMP108]], 3
; CHECK-NEXT:    [[TMP110:%.*]] = trunc i64 [[TMP109]] to i8
; CHECK-NEXT:    [[TMP111:%.*]] = icmp sge i8 [[TMP110]], [[TMP106]]
; CHECK-NEXT:    [[TMP112:%.*]] = and i1 [[TMP107]], [[TMP111]]
; CHECK-NEXT:    [[TMP113:%.*]] = call i64 @llvm.amdgcn.ballot.i64(i1 [[TMP112]])
; CHECK-NEXT:    [[TMP114:%.*]] = icmp ne i64 [[TMP113]], 0
; CHECK-NEXT:    br i1 [[TMP114]], label [[ASAN_REPORT4:%.*]], label [[TMP117:%.*]], !prof [[PROF2]]
; CHECK:       asan.report4:
; CHECK-NEXT:    br i1 [[TMP112]], label [[TMP115:%.*]], label [[TMP116:%.*]]
; CHECK:       115:
; CHECK-NEXT:    call void @__asan_report_store4(i64 [[TMP102]]) #[[ATTR6]]
; CHECK-NEXT:    call void @llvm.amdgcn.unreachable()
; CHECK-NEXT:    br label [[TMP116]]
; CHECK:       116:
; CHECK-NEXT:    br label [[TMP117]]
; CHECK:       117:
; CHECK-NEXT:    store i32 [[TMP99]], ptr addrspace(1) [[TMP101]], align 4
; CHECK-NEXT:    br label [[CONDFREE:%.*]]
; CHECK:       CondFree:
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier()
; CHECK-NEXT:    br i1 [[XYZCOND]], label [[FREE:%.*]], label [[END:%.*]]
; CHECK:       Free:
; CHECK-NEXT:    [[TMP118:%.*]] = call ptr @llvm.returnaddress(i32 0)
; CHECK-NEXT:    [[TMP119:%.*]] = ptrtoint ptr [[TMP118]] to i64
; CHECK-NEXT:    [[TMP120:%.*]] = ptrtoint ptr addrspace(1) [[TMP21]] to i64
; CHECK-NEXT:    call void @__asan_free_impl(i64 [[TMP120]], i64 [[TMP119]])
; CHECK-NEXT:    br label [[END]]
; CHECK:       End:
; CHECK-NEXT:    ret void
;
  %1 = load volatile i32, ptr addrspace(1) %arg0
  %2 = atomicrmw umin ptr addrspace(3) @lds_1, i32 %1 seq_cst
  %3 = atomicrmw umax ptr addrspace(3) @lds_1, i32 %1 seq_cst
  %4 = add i32 %2, %3
  store i32 %4, ptr addrspace(3) @lds_2, align 4
  ret void
}
!llvm.module.flags = !{!0}
!0 = !{i32 4, !"nosanitize_address", i32 1}

;.
; CHECK: attributes #[[ATTR0]] = { sanitize_address "amdgpu-lds-size"="8" }
; CHECK: attributes #[[ATTR1:[0-9]+]] = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
; CHECK: attributes #[[ATTR2:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(none) }
; CHECK: attributes #[[ATTR3:[0-9]+]] = { convergent nocallback nofree nounwind willreturn }
; CHECK: attributes #[[ATTR4:[0-9]+]] = { convergent nocallback nofree nounwind willreturn memory(none) }
; CHECK: attributes #[[ATTR5:[0-9]+]] = { convergent nocallback nofree nounwind }
; CHECK: attributes #[[ATTR6]] = { nomerge }
;.
; CHECK: [[META0]] = !{i32 0, i32 1}
; CHECK: [[META1:![0-9]+]] = !{i32 4, !"nosanitize_address", i32 1}
; CHECK: [[PROF2]] = !{!"branch_weights", i32 1, i32 100000}
;.
