; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5

; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 -passes=instcombine,slp-vectorizer -S < %s | FileCheck %s

define internal fastcc void @test(ptr %out, i64 %in0, i64 %in1) unnamed_addr #18 align 2 {
; CHECK-LABEL: define internal fastcc void @test(
; CHECK-SAME: ptr [[OUT:%.*]], i64 [[IN0:%.*]], i64 [[IN1:%.*]]) unnamed_addr #[[ATTR0:[0-9]+]] align 2 {
; CHECK-NEXT:    [[VEC0:%.*]] = bitcast i64 [[IN0]] to <4 x i16>
; CHECK-NEXT:    [[VEC1:%.*]] = bitcast i64 [[IN1]] to <4 x i16>
; CHECK-NEXT:    store <4 x i16> [[VEC0]], ptr [[OUT]], align 1
; CHECK-NEXT:    [[P4:%.*]] = getelementptr inbounds nuw i8, ptr [[OUT]], i64 8
; CHECK-NEXT:    store <4 x i16> [[VEC1]], ptr [[P4]], align 1
; CHECK-NEXT:    ret void
;
  %vec0 = bitcast i64 %in0 to <4 x i16>
  %vec0.expand= shufflevector <4 x i16> %vec0, <4 x i16> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
  %vec1 = bitcast i64 %in1 to <4 x i16>
  %vec1.expand = shufflevector <4 x i16> %vec1, <4 x i16> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
  %vecblend = shufflevector <8 x i16> %vec0.expand, <8 x i16> %vec1.expand, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
  %ele0 = extractelement <8 x i16> %vecblend, i32 0
  store i16 %ele0, ptr %out, align 1
  %ele1 = extractelement <8 x i16> %vecblend, i32 1
  %p1 = getelementptr inbounds i16, ptr %out, i64 1
  store i16 %ele1, ptr %p1, align 1
  %ele2 = extractelement <8 x i16> %vecblend, i32 2
  %p2 = getelementptr inbounds i16, ptr %out, i64 2
  store i16 %ele2, ptr %p2, align 1
  %ele3 = extractelement <8 x i16> %vecblend, i32 3
  %p3 = getelementptr inbounds i16, ptr %out, i64 3
  store i16 %ele3, ptr %p3, align 1
  %ele4 = extractelement <8 x i16> %vecblend, i32 4
  %p4 = getelementptr inbounds i16, ptr %out, i64 4
  store i16 %ele4, ptr %p4, align 1
  %ele5 = extractelement <8 x i16> %vecblend, i32 5
  %p5 = getelementptr inbounds i16, ptr %out, i64 5
  store i16 %ele5, ptr %p5, align 1
  %ele6 = extractelement <8 x i16> %vecblend, i32 6
  %p6 = getelementptr inbounds i16, ptr %out, i64 6
  store i16 %ele6, ptr %p6, align 1
  %ele7 = extractelement <8 x i16> %vecblend, i32 7
  %p7 = getelementptr inbounds i16, ptr %out, i64 7
  store i16 %ele7, ptr %p7, align 1
  ret void
}
